# Basic Fuctions

In [1]:
import numpy as np
array1 = np.array([[2,3,34,4,7,4,7,3],
                  [2,3,34,4,7,4,7,3]])
print(array1)
print(type(array1))

[[ 2  3 34  4  7  4  7  3]
 [ 2  3 34  4  7  4  7  3]]
<class 'numpy.ndarray'>


In [2]:
array1.sum()

128

In [3]:
array1.mean()

8.0

In [4]:
print(array1)

[[ 2  3 34  4  7  4  7  3]
 [ 2  3 34  4  7  4  7  3]]


# Slicing

In [5]:
array1

array([[ 2,  3, 34,  4,  7,  4,  7,  3],
       [ 2,  3, 34,  4,  7,  4,  7,  3]])

In [6]:
arryay3 = np.array([3,4,4,44,4,4])

In [7]:
arr = arryay3[4:6]

In [8]:
arr

array([4, 4])

In [9]:
arr[0] = 102333232

In [10]:
arryay3.sort()

In [11]:
arryay3

array([        3,         4,         4,         4,        44, 102333232])

# More on Numpy

In [12]:
ar1 = np.array([[1,2,3,4,5],
              [24,5,6,4,6]])

In [13]:
ar1.sum()

60

In [14]:
ar1.sum(axis=1)

array([15, 45])

In [15]:
ar1.sum(axis=0)

array([25,  7,  9,  8, 11])

In [16]:
ar2 = np.array([[7,8,9,10,11],
              [3,456,789,43,33]])

In [17]:
ar1.transpose()

array([[ 1, 24],
       [ 2,  5],
       [ 3,  6],
       [ 4,  4],
       [ 5,  6]])

In [18]:
ar1.dot(ar2.transpose())

array([[ 145, 3619],
       [ 368, 7456]])

In [19]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [20]:
np.void(2)

void(b'\x00\x00')

In [21]:
ar1.round()

array([[ 1,  2,  3,  4,  5],
       [24,  5,  6,  4,  6]])

In [22]:
ar1

array([[ 1,  2,  3,  4,  5],
       [24,  5,  6,  4,  6]])

In [23]:
ar3 = np.ar1[3:6]

AttributeError: module 'numpy' has no attribute 'ar1'

In [24]:
len(dir(np))

606

In [25]:
np.add(ar1,ar2)

array([[  8,  10,  12,  14,  16],
       [ 27, 461, 795,  47,  39]])

In [26]:
np.sort(ar1)

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  6, 24]])

In [27]:
np.sort(ar2,axis=0)

array([[  3,   8,   9,  10,  11],
       [  7, 456, 789,  43,  33]])

In [28]:
np.array(ar1)

array([[ 1,  2,  3,  4,  5],
       [24,  5,  6,  4,  6]])

In [29]:
np.sort(ar1,axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  6, 24]])

In [31]:
a = np.arange(5)

In [32]:
a

array([0, 1, 2, 3, 4])

In [75]:
b=np.array([2,3,2,32,321,3213,123,123,213,13,123,131,31,231,312,321,312,3])
b = b.reshape(6,3)

In [76]:
b

array([[   2,    3,    2],
       [  32,  321, 3213],
       [ 123,  123,  213],
       [  13,  123,  131],
       [  31,  231,  312],
       [ 321,  312,    3]])

In [77]:
# b.sort()
print(b)

[[   2    3    2]
 [  32  321 3213]
 [ 123  123  213]
 [  13  123  131]
 [  31  231  312]
 [ 321  312    3]]


In [79]:
np.argsort(b,axis=0)

array([[0, 0, 0],
       [3, 2, 5],
       [4, 3, 3],
       [1, 4, 2],
       [2, 5, 4],
       [5, 1, 1]], dtype=int64)

In [73]:
np.argmin(b)

0

In [74]:
np.argmax(b)

5